### ISSUE TITLE
no build/ directory generated after make

### ISSUE THREAD

**Issue by mgiannini** [mongodb/specifications#1159]
I ran `make` in the `source/` directory and it ran and appeared to modify a ton of json files, but I do not see that a `build/` directory was generated. Can you help point out what I'm doing wrong? Or even better, is there a website that has all the PDF specifications already generated for download?

**Comment by jmikola** [comment]
This project does not currently utilize Makefiles for building/processing the RST sources.

If you look at the [Makefile](https://github.com/mongodb/specifications/blob/master/source/Makefile), you'll see that it is only used to generate JSON from the corresponding YAML spec test files. We also use a [Makefile](https://github.com/mongodb/specifications/blob/master/source/unified-test-format/tests/Makefile) in the unified test format spec to validate spec test files against a JSON schema.

> is there a website that has all the PDF specifications already generated for download?

We do not publish spec files as PDFs, but you may be able to feed the RST files to a separate PDF conversion tool (e.g. [rst2pdf](https://rst2pdf.org/)). Alternatively, view the rendered specs in GitHub and print the page to a PDF for offline viewing.

**Comment by mgiannini** [comment]
Thanks - I didn't realize github rendered rst files. So that is sufficient for me.

**Comment by ShaneHarvey** [comment]
We should update the readme: https://github.com/mongodb/specifications#building-documents

It also appears that "bin/builder.py" no longer works:
```
$ pypy bin/builder.py
Traceback (most recent call last):
  File "bin/builder.py", line 95, in <module>
    makefile = GeneratedMakefile()
  File "bin/builder.py", line 90, in __init__
    for (src, trg, shc) in generate_file_tree(dir):
  File "bin/builder.py", line 24, in generate_file_tree
    if source.rsplit('.',1)[1] == "tmpl":
IndexError: list index out of range
```

**Comment by jmikola** [comment]
> We should update the readme: https://github.com/mongodb/specifications#building-documents

I completely forgot about that section. Feel free to open a PR removing the section and tag me as a reviewer if needed.
