### ISSUE TITLE
Why maxIdleTimeMs defaults to zero?

### ISSUE THREAD

**Issue by fredmaggiowski** [mongodb/specifications#1476]
While investigating some issues about connection management in one of the services of my application I stumbled upon the `maxIdleTimeMs` default value which is set to 0 meaning that there is no idle limit and therefore connection may remain unused but still active.

I was wondering why is that so? 

Reading [this FAQ](https://www.mongodb.com/docs/drivers/node/current/faq/#how-does-connection-pooling-work-in-the-node-driver-) (specific to Node.js driver) I see there are concerns about the application being in charge of dealing with pool configuration tuning, so I guess the problem is to find an "ideal" time that works for most of the scenarios?

**Comment by alexbevi** [comment]
Hey @fredmaggiowski, and thanks for the question. There is nothing inherently wrong with an idle socket, and the driver doesn’t know when it might be needed again, so we decided not to close it after some arbitrary period of time (by default at least).

**Comment by fredmaggiowski** [comment]
Hi @alexbevi thanks for your reply

>There is nothing inherently wrong with an idle socket, and the driver doesn’t know when it might be needed again

I agree, however depending on the server provider there may be a limit on available connections and keeping them open could cause issue.

> ... and the driver doesn’t know when it might be needed again, so we decided not to close it after some arbitrary period of time (by default at least).

I agree that there is no way for the driver to know this and now understand why the decision has been made.

Thanks!
