### ISSUE TITLE
Broken link mongoc-handshake.c

### ISSUE THREAD

**Issue by manfontan** [mongodb/specifications#172]
There is a broken link in the handshake specification.

I have attached the patch.diff in txt format as issues do not support .diff format uploads and I don't have fork permission on this repo to make pull requests.

[patch.txt](https://github.com/mongodb/specifications/files/1218155/patch.txt)

Best regards,

Manuel.

**Comment by jmikola** [comment]
Converted your patch to a commit (https://github.com/mongodb/specifications/commit/248f8cdd11759be2ba09adb4a1406e95c2391f2d) and merged in https://github.com/mongodb/specifications/commit/bad12deb40c631a974d7036267e87a819abf0f14. Thanks!
