### ISSUE TITLE
Validate spec test format using JSON schema

### ISSUE THREAD

**Issue by ShaneHarvey** [mongodb/specifications#516]
@mbroadst [brought up the idea of using JSON schema](https://github.com/mongodb/specifications/pull/500#issuecomment-470638425
):

> Cool! I think we should also put together JSON schema for the transaction test runner format, and use that to verify that tests ascribing to that format are properly formatted.

This would be nice to integrate into Travis after #501.

**Comment by mbroadst** [comment]
Thanks Shane 👍

**Comment by blink1073** [comment]
This is done: https://github.com/mongodb/specifications/blob/3c7d132907d6f485f3abfbfa77103aaceceb94f6/.github/workflows/unified-test-format-schema-check.yml
