### ISSUE TITLE
Regenerate templated spec test files in Travis 

### ISSUE THREAD

**Issue by ShaneHarvey** [mongodb/specifications#655]
Various spec tests are generated via scripts. We should integrate these scripts with Travis to validate that the template files have been updated correctly.

Examples:
- Transaction tests: https://github.com/mongodb/specifications/blob/5b9cbb49a0e386a91da3b98d1a8cff3caaffaf17/source/transactions/tests/mongos-pin-auto-tests.py
- Client side encryption: https://github.com/mongodb/specifications/tree/5b9cbb49a0e386a91da3b98d1a8cff3caaffaf17/source/client-side-encryption/etc

**Comment by ShaneHarvey** [comment]
Note: I did this for the new 4.4+ SDAM tests in https://github.com/mongodb/specifications/commit/371e95b18f4783d485218bb1565970be10568e8a:
```
     - name: "JSON regeneration check"
-      dist: trusty
-      language: node_js
-      node_js:
-        - 12
+      dist: xenial
+      language: python
+      python:
+        - 3.7
       install:
         - npm install -g js-yaml
       script:
+        - python3 ./source/server-discovery-and-monitoring/tests/errors/generate-error-tests.py
         - cd source && make && git diff --exit-code
``` 

We should still do the same for the transactions and encryption tests.

**Comment by blink1073** [comment]
This is done: https://github.com/mongodb/specifications/blob/3c7d132907d6f485f3abfbfa77103aaceceb94f6/.github/workflows/json-regenerate-check.yml
