### ISSUE TITLE
Please Add "Sign up with Google Account" option at cloud.mongodb.com/user

### ISSUE THREAD

**Issue by Donboscow** [mongodb/specifications#680]
Add Sign up with Google Account feature in cloud.mongodb.com/user web console. I am missing this feature very badly.

**Comment by mbroadst** [comment]
Hi @Donboscow. This is a repository used by the MongoDB Drivers team to openly document the specifications for building a driver. If you'd like support with MongoDB Atlas, or to recommend a feature, please visit the [Atlas support docs](https://docs.atlas.mongodb.com/support/) or use the intercom button in your Atlas dashboard (the small green circle at the bottom right of the screen).
