### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by internalfx** [mongodb/specifications#79]
What is the GridFS specification licensed under?

**Comment by ajdavis** [comment]
That's a great question, and I'm sorry for the delay in answering it. All our drivers' implementations of the spec are Apache 2 licensed, but we haven't chosen a license for the spec, or any specs. Why do you ask, please?

**Comment by internalfx** [comment]
I was planning on adapting it for another project, but in the end I decided to write it from scratch.

So we're good.

**Comment by ajdavis** [comment]
Thanks, @internalfx. In any case your question (once I noticed it here) prompted a useful discussion about how to license our non-code intellectual output.

**Comment by internalfx** [comment]
@ajdavis Glad to hear it...

I've chosen ISC myself...

https://github.com/internalfx/regrid-spec
