### ISSUE TITLE
What is the actual purpose of giving a name for a replica set?

### ISSUE THREAD

**Issue by alitoufighi** [mongodb/specifications#851]
I have read server discovery specs, specifically [TopologyDescription](https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst#topologydescription) part. For me (completely unaware of internal implementation of servers), the `servers` part of this data structure seems to be the unique identifier of that replica set.

Hence, actually I didn't figure out why a replica set must have a name, and why a client is required to pass this name when connecting to this replica set. The only thing I found was a comment [here](https://jira.mongodb.org/browse/SERVER-47910?focusedCommentId=3070143&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-3070143):

>   Drivers use setname to ensure the list of hosts you specified actually matches that setname for all hosts.

But, why? By providing a seed list in connection string, I'm connecting to a replica set, which its `mongod` instances are up on specified (host, port) pairs. Isn't this enough for identifying the replica set?

Is there a case where a server can be part of more than one replica sets? [This answer](https://stackoverflow.com/a/28506579/8543203) says no. If so, why a client must have concern of the `setName`?

To be more precise, what would be wrong with following connection string to show connecting to a replica set?
`mongodb://user:pass@localhost:27017/?replicaSet=true`

**Comment by p-mongo** [comment]
Specifying the replica set name verifies that the client is connecting to the expected replica set.

Some drivers permitted the replica set name to be omitted and discovered the name automatically. I believe mongo shell required replica set name to be specified if a replica set connection was desired; I don't remember if any of the drivers had the same behavior. Some of the drivers would discover replica set name if you specified more than one seed; naturally this wouldn't work for a single-node replica set.

Automatic discovery  of replica set name was implemented as part of https://github.com/mongodb/specifications/pull/739.
