### ISSUE TITLE
We're introducing the directConnection URI option in the next PyMongo release. We'll change the default behavior in PyMongo 4.0.

### ISSUE THREAD

**Issue by Constancejackson98** [mongodb/specifications#858]
We're introducing the directConnection URI option in the next PyMongo release. We'll change the default behavior in PyMongo 4.0.

_Originally posted by @behackett in https://github.com/mongodb/specifications/issues/801#issuecomment-627540277_

**Comment by Constancejackson98** [comment]
So what direct connect would that be?

**Comment by behackett** [comment]
See the directConnection option documented in "Parameters" here:https://pymongo.readthedocs.io/en/stable/api/pymongo/mongo_client.html#pymongo.mongo_client.MongoClient

**Comment by Constancejackson98** [comment]
Thank you for the update. I missed one of the previous emails.
