### ISSUE TITLE
"fast fail" with serverSelectionTimeoutMS

### ISSUE THREAD

**Issue by gregbanks** [mongodb/specifications#87]
Hi,

As written, the spec seems to ignore a use case that is quite important: the ability to get feedback immediately if a server or cluster is down at client creation. A concrete example of where this might be problematic is a status probe. You can imagine writing a small script to run as part of a monitoring tool like Munin that reports the number of current connections and looks something like:

```
import os
import sys

from pymongo.mongo_client import MongoClient

def main():
    if len(sys.argv) < 2:
        try:
            client = MongoClient(os.environ.get('MUNIN_MONGODB_CUR_CONN_CNT_URI',
                                                'mongodb://127.0.0.1:27017'),
                                 connect=True)
            status = client.get_database('admin').command({'serverStatus': 1})
            print 'status.value {}'.format(status['connections']['current'])
        except Exception:
            print 'status.value 0'
    elif sys.argv[1] == 'config':
        print """\
graph_title Current MongoDB Connections
graph_vlabel Connections
status.label Connections
"""
    return 0

if __name__ == '__main__':
    sys.exit(main())
```

Using `pymongo==2.8`, I get immediate feedback if the server is down in the form of a `ConnectionFailure` (e.g., `pymongo.errors.ConnectionFailure: [Errno 61] Connection refused`). Using `pymongo==3.2`, I am forced to wait for the entire duration of `serverSelectionTimeoutMS` (defaulting to 30s) which is incredibly inconvenient. Of course, you can set `serverSelectionTimeoutMS` to be something small like 1ms, which will give you immediate feedback, however you are now racing against the background monitoring threads making the actual connections and, unless you are connecting to a local instance, you will likely get a `ServerSelectionTimeoutError` even if the server is up (this is the “fail fast” method mentioned in the [spec](https://github.com/mongodb/specifications/blob/master/source/server-selection/server-selection.rst#serverselectiontimeoutms)). Regardless, in this context, it doesn’t make much sense to set `serverSelectionTimeoutMS` to be less than `connectTimeoutMS`, since, by definition, you are indicating that you are willing to wait up to `connectTimeoutMS` to allow the underlying socket connection to be established with a server.

Given the situation described above, I would suggest updating the spec to add a section describing how to “fail fast” in this context. It might be that another option is required to be passed to `MongoClient` to “fail fast” on initial connection. In this case, the `Topology` class might raise a `ConnectionFailure` or `ServerSelectionError` in `Topology.select_servers` if a socket error is raised for that server indicating that there is nothing listening on the foreign port during a period of `connectTimeoutMs` after `Topology.open` has been called (thereby starting the monitoring threads).

I apologize if this is too `pymongo` specific, but this is the manifestation of the spec that I am most familiar with.

Cheers,
Greg

**Comment by bjori** [comment]
Try using [serverSelectionTryOnce](https://github.com/mongodb/specifications/blob/master/source/server-selection/server-selection.rst#serverselectiontryonce). That is meant to solve this issue

**Comment by behackett** [comment]
PyMongo, by nature of its support for and use of threads, does not implement serverSelectionTryOnce. PyMongo is actually forbidden from implementing the option by the spec.

See the definition of serverSelectionTimeoutMS for an explanation of why 30 seconds was chosen:

https://github.com/mongodb/specifications/blob/master/source/server-selection/server-selection.rst#serverselectiontimeoutms

You're only option for fail fast is to lower the value of serverSelectionTimeoutMS

**Comment by gregbanks** [comment]
I did see that option, however the spec explicitly forbids multi-threaded drivers from implementing this:
```
Multi-threaded drivers MUST NOT provide this mode.
```
 so, unfortunately, it is not a solution in this context.

**Comment by gregbanks** [comment]
I completely understand (and agree with!) the rational for defaulting `serverSelectionTimeoutMS` to 30 seconds in a long running application. However, it does not seem to be appropriate when writing short lived or interactive applications, as described above, especially when there is feedback (like "connection refused") that would allow the application to react immediately and as expected. 

You could, of course, set a low `serverSelectionTimeoutMS` that would be acceptable and wrap any calls to `MongoClient` that would end up invoking `Topology.select_servers` with a function that would loop over that call, catching `ServerSelectionTimeoutError`s until it got a result or a `ServerSelectionTimeoutError` that contained information about the underlying socket error (e.g. "connection refused"), but polling like that seems a bit inefficient.

**Comment by ajdavis** [comment]
Hi, I completely understand your objection to the changes we made to PyMongo. For the sake of simplicity, we decided to improve the common use case in multi-threaded, and *not* support the use case you're describing anymore. I know it leaves you without good support for what you want to do.

One idea is to simply create a socket, call settimeout, and connect the socket to the target host on port 27017. If it connects, there's a server listening. Do you think it'd be helpful to put an example of this in PyMongo's FAQ and other drivers' FAQs?

**Comment by gregbanks** [comment]
Hi Jesse,

My apologies for the delayed response!

The solution you suggest is the solution I previously implemented as a short-term fix. If this is the endorsed pattern to "fail fast" at client creation in a multi-threaded driver, I do think it would be helpful to document it in order to save other folks some time/confusion.

As to your point about simplicity, are you trying to simplify the end user experience or are you trying to simplify the development/support on MongoDB’s side? I imagine the answer is both, however, I can see this all-or-nothing approach leading to more questions/issues as the people whose use cases are no longer supported are forced to deviate from the official path. Maybe you, or someone else, can elaborate a bit on the perceived cost associated with support for use cases like these?

Thanks!

Cheers,
Greg

**Comment by ajdavis** [comment]
Right, the answer is both: by not implementing anything like
serverSelectionTryOnce in multi-threaded drivers, we accomplish a lot:

- fewer knobs for users
- prevent users from making what is typically the wrong decision
- prevent the Server Selection Spec
<https://github.com/mongodb/specifications/blob/master/source/server-selection/server-selection.rst>,
which is complex, from growing more so

In any case, "try once" or "fail fast" is difficult to define for a
multi-threaded driver. It used to be easy to define in PyMongo 2.8. That
version had an inferior concurrency model whose sole advantage was it would
sometimes fail quickly if you happen to write your URL wrong. Now in
PyMongo 3+, we have a very good concurrency model for production systems,
but it's less convenient if you're testing whether you wrote your URL right.

I knew we were making this tradeoff, and I think it's the right one.

If you want to know more about the new behavior, I wrote Server Discovery
And Monitoring In PyMongo, Perl, And C
<https://emptysqua.re/blog/server-discovery-and-monitoring-in-pymongo-perl-and-c/>
and
gave a talk on it at MongoDB World
<https://www.mongodb.com/presentations/mongodb-drivers-and-high-availability-deep-dive>
last year.

Thanks for listening,
J

**Comment by gregbanks** [comment]
Hey,

Thanks for the explanation. I'm familiar with your blog (e.g., [It Seemed Like A Good...](https://emptysqua.re/blog/good-idea-at-the-time-pymongo-start-request/#mongoclient)), understand the motivations, and really appreciate a lot of the things you guys are doing (including specing these things out!). I guess I was hoping that something like the hybrid approach might be taken with other drivers.

As to the use case itself, I think that characterizing it as "testing whether you wrote your URL right" is a bit unfair as it does apply to other less trivial scenarios (see the monitoring example above). Regardless of whether or not you are using a multi-threaded or single-threaded driver, I feel that the justification for "try once" still applies (i.e., `Minimizing response latency is important for maximizing request-handling capacity and for *user experience* (e.g. a quick fail message instead of a slow web page)`)

Despite these things, I think that I can accomplish what I want, while still coloring within the lines, by taking advantage of the monitoring mechanism and, until server heartbeat listener/events are released, the"deep customization" hooks you've provided in `pymongo`.

Thanks again and I look forward to your upcoming talk (although, unfortunately, I'm on the wrong coast to come see it in person...).

Cheers,
Greg

**Comment by ajdavis** [comment]
Thanks for your kind words, Greg!
