### ISSUE TITLE
Insertion of hashMap<String,Object> greater than 16 mb

### ISSUE THREAD

**Issue by sudhavk** [mongodb/specifications#89]
Facing an issue with the hashMap<String,Object> greater than 16 mb.I looked at the gridfs and it doesnt have any support for the DBObject.Please let me know the Solution.

hashMap saves  unitName and data of length > 16Mb.It is not persisting in the mongo database.

Regards,
Sudha

**Comment by ajdavis** [comment]
Please read this page about how to ask for help with MongoDB:

https://docs.mongodb.com/manual/support/#community-support
